app/models.py
from . import db

# setiap class adalah table di database
class Contact(db.Model):
    id: int = db.Column(db.Integer, primary_key = True)
    name: str = db.Column(db.String(80), nullable=False)
    no_hp: str = db.Column(db.String(15), nullable=False, unique=True)
    email: str = db.Column(db.String(30), nullable=False)

    # representasi string dari objek, bagus buat debug
    def __repr__(self):
        return f"<Contact {self.name}>"

app/__init__.py
# import libraries
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from dotenv import load_dotenv

# load env
load_dotenv()

# inisialiasasi SQLAlchemy
db: SQLAlchemy = SQLAlchemy()

def create_app():
    app: Flask = Flask(__name__)

    abs_path = os.path.abspath(os.path.dirname(__file__))

    # konfigurasi aplikasi
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{os.path.join(abs_path, "contact.db")}"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # koneksikan database sqlalchemy dengan flask
    db.init_app(app)

    # inilisiasliasi routing
    from . import routes
    app.register_blueprint(routes.main)

    return app

app/routes.py
# import semua libraries
from flask import Blueprint, request, redirect, render_template, url_for, flash
from .models import Contact
from . import db
from sqlalchemy.exc import IntegrityError
from app.utils.validators import validate_contact

main = Blueprint('main', __name__)

# test
@main.route("/")
def index():

    contacts = Contact.query.all()

    return render_template("index.html", contacts=contacts)

@main.route("/add", methods=["POST", "GET"])
def add():
    if request.method == "POST":
        nama: str = request.form['nama'].strip()
        no_hp: str = request.form['no_hp'].strip()
        email: str = request.form['email'].strip()

        # validator
        errors: list = validate_contact(nama=nama, no_hp=no_hp, email=email)
        if errors:
            for err in errors:
                flash(err, "failed")
                return redirect(url_for('main.add'))

        else:
            new_user: Contact = Contact(name=nama, no_hp=no_hp, email=email)
            try:
                db.session.add(new_user)
                db.session.commit()
                flash("Berhasil menambahkan data", "success")
                return redirect(url_for('main.index'))
            except IntegrityError:
                db.session.rollback()
                flash("Data dengan email / no HP itu sudah ada!", "failed")
                return redirect(url_for('main.add'))
            except Exception as e:
                db.session.rollback()
                flash(f"Gagal menambahkan data: {e}", "failed")
                return redirect(url_for('main.index'))

    return render_template("add.html")

@main.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    # dapatkan 1 user sesuai dengan id
    user = Contact.query.get_or_404(id)

    # ubah data
    if request.method == "POST":
        name: str = request.form['nama'].strip()
        no_hp: str = request.form['no_hp'].strip()
        email: str = request.form['email'].strip()

        # validator
        errors: list = validate_contact(nama=name, no_hp=no_hp, email=email, exclude_id= user.id)
        if errors:
            for err in errors:
                flash(err, "failed")
            return redirect(url_for('main.edit', id = user.id))
        else:

            user.name = name
            user.no_hp = no_hp
            user.email = email

            try:
                db.session.commit()
                flash("Berhasil edit data cihuy")
                return redirect(url_for('main.index'))
            except IntegrityError:
                db.session.rollback()
                flash("Email atau No HP sudah digunakan")
                return redirect(url_for("main.edit", id=user.id))
            except Exception as e:
                db.session.rollback()
                flash(f"Error like that shit {e}")
        
    return render_template("edit.html", user=user)

@main.route('/delete/<int:id>', methods=['GET'])

def delete(id):
    user = Contact.query.get_or_404(id)

    try:
        db.session.delete(user)
        db.session.commit()
        flash("Data berhasil dihapus")
    except:
        db.session.rollback()
        flash("Data gagal di hapus")
    
    return redirect(url_for('main.index'))

app/templates/add.html
{% extends "base.html" %} {% block form_add %}

<form action="{{url_for('main.add')}}" method="post">
  <table>
    <tr>
      <td><label for="nama">Nama </label></td>
      <td>:</td>
      <td><input type="text" name="nama" id="nama" /></td>
    </tr>
    <tr>
      <td><label for="no_hp">No HP</label></td>
      <td>:</td>
      <td><input type="text" name="no_hp" id="no_hp" /></td>
    </tr>
    <tr>
      <td><label for="email">Email </label></td>
      <td>:</td>
      <td><input type="text" name="email" id="email" /></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><input type="submit" value="Simpan data" /></td>
    </tr>
  </table>
</form>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CONTACT APP</title>
    <style>
      .success {
        color: green;
      }
      .failed {
        color: red;
      }
    </style>
  </head>
  <body>
    <h1>INI SEBUAH JUDUL KIMAK</h1>
    {% with messages = get_flashed_messages(with_categories=True) %} {% if
    messages %} {% for category, msg in messages %}
    <p class="{{category}}">{{msg}}</p>
    {% endfor %} {% endif %} {% endwith %}
    <div>{% block main %} {% endblock %}</div>
    <div>{% block form_add %} {% endblock %}</div>
  </body>
</html>

app/templates/edit.html
{% extends "base.html" %} {% block form_add %}

<form action="{{url_for('main.edit', id=user.id)}}" method="post">
  <table>
    <tr>
      <td><label for="nama">Nama </label></td>
      <td>:</td>
      <td><input type="text" name="nama" id="nama" value="{{user.name}}" /></td>
    </tr>
    <tr>
      <td><label for="no_hp">No HP</label></td>
      <td>:</td>
      <td>
        <input type="text" name="no_hp" id="no_hp" value="{{user.no_hp}}" />
      </td>
    </tr>
    <tr>
      <td><label for="email">Email </label></td>
      <td>:</td>
      <td>
        <input type="text" name="email" id="email" value="{{user.email}}" />
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><input type="submit" value="Simpan Perubahan" /></td>
    </tr>
  </table>
</form>

{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block main %}
<div>
  <table border="1">
    <tr>
      <th>NAME</th>
      <th>NO HP</th>
      <th>EMAIL</th>
      <th>ACTION</th>
    </tr>
    {% if not contacts %}
    <tr>
      <td colspan="4">BELUM ADA DATA</td>
    </tr>
    {% else %} {% for contact in contacts %}
    <tr>
      <td>{{contact.name}}</td>
      <td>{{contact.no_hp}}</td>
      <td>{{contact.email}}</td>
      <td>
        <a href="{{url_for('main.edit', id=contact.id)}}">Edit</a> ||
        <a href="{{url_for('main.delete', id=contact.id)}}">Delete</a>
      </td>
    </tr>
    {% endfor %} {% endif %}
  </table>
  <a href="{{url_for('main.add')}}">TAMBAH DATA</a>
</div>
{% endblock %}